require_relative "../helpers"

module Metacrunch::UBPB::Transformations::MabToPrimo::Helpers::PersonRelationshipDesignator
  MAPPING = {
    "rcp" => { "de" => "Adressat", "en" => "addressee" },
    "dgs" => { "de" => "Akademischer Betreuer", "en" => "degree supervisor" },
    "dfd" => { "de" => "Angeklagter/Beklagter", "en" => "defendant" },
    "ann" => { "de" => "Annotierende Person", "en" => "annotator" },
    "arc" => { "de" => "Architekt", "en" => "architect" },
    "arr" => { "de" => "Arrangeur", "en" => "arranger" },
    "std" => { "de" => "Art Director", "en" => "set designer" },
    "prf" => { "de" => "Ausführender", "en" => "performer" },
    "csl" => { "de" => "Berater", "en" => "consultant" },
    "ape" => { "de" => "Berufungsbeklagter/Revisionsbeklagter", "en" => "appellee" },
    "apl" => { "de" => "Berufungskläger/Revisionskläger", "en" => "appellant" },
    "ins" => { "de" => "Beschriftende Person", "en" => "inscriber" },
    "scl" => { "de" => "Bildhauer", "en" => "sculptor" },
    "vdg" => { "de" => "Bildregisseur", "en" => "videographer" },
    "brl" => { "de" => "Brailleschriftpräger", "en" => "braille embosser" },
    "bnd" => { "de" => "Buchbinder", "en" => "binder" },
    "bkd" => { "de" => "Buchgestalter", "en" => "book designer" },
    "sgd" => { "de" => "Bühnenregisseur", "en" => "stage director" },
    "chr" => { "de" => "Choreograph", "en" => "choreographer", "german_shortcut" => "Choreogr."},
    "edm" => { "de" => "Cutter", "en" => "editor of moving image work" },
    "dsr" => { "de" => "Designer", "en" => "designer" },
    "cnd" => { "de" => "Dirigent", "en" => "conductor", "german_shortcut" => "Dir." },
    "pan" => { "de" => "Diskussionsteilnehmer", "en" => "panelist" },
    "aus" => { "de" => "Drehbuchautor", "en" => "screenwriter" },
    "prt" => { "de" => "Drucker", "en" => "printer" },
    "plt" => { "de" => "Druckformhersteller", "en" => "platemaker" },
    "prm" => { "de" => "Druckgrafiker", "en" => "printmaker" },
    "own" => { "de" => "(Gegenwärtiger) Eigentümer", "en" => "owner" },
    "inv" => { "de" => "Erfinder", "en" => "inventor" },
    "nrt" => { "de" => "Erzähler", "en" => "narrator" },
    "tlp" => { "de" => "Fernsehproduzent", "en" => "television producer" },
    "tld" => { "de" => "Fernsehregisseur", "en" => "television director" },
    "fmk" => { "de" => "Filmemacher", "en" => "filmmaker" },
    "fmp" => { "de" => "Filmproduzent", "en" => "film producer" },
    "fmd" => { "de" => "Filmregisseur", "en" => "film director" },
    "fds" => { "de" => "Filmvertrieb", "en" => "film distributor" },
    "cas" => { "de" => "Formgießer", "en" => "caster" },
    "pht" => { "de" => "Fotograf", "en" => "photographer", "german_shortcut" => "Fotogr." },
    "fmo" => { "de" => "Früherer Eigentümer", "en" => "former owner" },
    "hst" => { "de" => "Gastgeber", "en" => "host" },
    "hnr" => { "de" => "Gefeierter", "en" => "honoree" },
    "crt" => { "de" => "Gerichtsstenograf", "en" => "court reporter" },
    "stl" => { "de" => "Geschichtenerzähler", "en" => "storyteller" },
    "egr" => { "de" => "Graveur", "en" => "engraver" },
    "isb" => { "de" => "Herausgebendes Organ", "en" => "issuing body" },
    "edt" => { "de" => "Herausgeber", "en" => "editor", "german_shortcut" => "Hrsg." },
    "rpc" => { "de" => "Hörfunkproduzent", "en" => "radio producer" },
    "rdd" => { "de" => "Hörfunkregisseur", "en" => "radio director" },
    "ill" => { "de" => "Illustrator", "en" => "illustrator", "german_shortcut" => "Ill." },
    "itr" => { "de" => "Instrumentalmusiker", "en" => "instrumentalist" },
    "ivr" => { "de" => "Interviewer", "en" => "interviewer" },
    "ive" => { "de" => "Interviewter", "en" => "interviewee" },
    "ctg" => { "de" => "Kartograf", "en" => "cartographer" },
    "wac" => { "de" => "Kommentarverfasser", "en" => "writer of added commentary" },
    "cmm" => { "de" => "Kommentator", "en" => "commentator", "german_shortcut" => "Komm." },
    "cmp" => { "de" => "Komponist", "en" => "composer", "german_shortcut" => "Komp." },
    "cst" => { "de" => "Kostümbildner", "en" => "costume designer" },
    "cur" => { "de" => "Kurator", "en" => "curator" },
    "art" => { "de" => "Künstler", "en" => "artist" },
    "abr" => { "de" => "Kürzender", "en" => "abridger" },
    "lsa" => { "de" => "Landschaftsarchitekt", "en" => "landscape architect" },
    "srv" => { "de" => "Landvermesser", "en" => "surveyor" },
    "tch" => { "de" => "Lehrer", "en" => "teacher" },
    "dpt" => { "de" => "Leihgeber", "en" => "depositor" },
    "lbt" => { "de" => "Librettist", "en" => "librettist" },
    "clt" => { "de" => "Lichtdrucker", "en" => "collotyper" },
    "ltg" => { "de" => "Lithograph", "en" => "lithographer" },
    "med" => { "de" => "Medium", "en" => "medium" },
    "mod" => { "de" => "Moderator", "en" => "moderator" },
    "msd" => { "de" => "Musikalischer Leiter", "en" => "musical director" },
    "osp" => { "de" => "On-Screen-Präsentator", "en" => "onscreen presenter" },
    "pre" => { "de" => "Präsentator", "en" => "presenter" },
    "pra" => { "de" => "Praeses", "en" => "praeses" },
    "pro" => { "de" => "Produzent", "en" => "producer", "german_shortcut" => "Prod." },
    "prg" => { "de" => "Programmierer", "en" => "programmer" },
    "mtk" => { "de" => "Protokollant", "en" => "minute taker" },
    "ppt" => { "de" => "Puppenspieler", "en" => "puppeteer" },
    "etr" => { "de" => "Radierer", "en" => "etcher" },
    "spk" => { "de" => "Redner", "en" => "speaker" },
    "drt" => { "de" => "Regisseur", "en" => "director" },
    "cor" => { "de" => "Registrar", "en" => "collection registrar" },
    "rsp" => { "de" => "Respondent", "en" => "respondent" },
    "rsr" => { "de" => "Restaurator", "en" => "restorationist" },
    "jud" => { "de" => "Richter", "en" => "judge" },
    "sng" => { "de" => "Sänger", "en" => "singer" },
    "col" => { "de" => "Sammler", "en" => "collector" },
    "brd" => { "de" => "Sender", "en" => "broadcaster" },
    "act" => { "de" => "Schauspieler", "en" => "actor" },
    "spn" => { "de" => "Sponsor", "en" => "sponsor" },
    "dnr" => { "de" => "Stifter", "en" => "donor" },
    "vac" => { "de" => "Synchronsprecher", "en" => "voice actor" },
    "prs" => { "de" => "Szenenbildner", "en" => "production designer" },
    "dnc" => { "de" => "Tänzer", "en" => "dancer" },
    "drm" => { "de" => "Technischer Zeichner", "en" => "draftsman" },
    "lyr" => { "de" => "Textdichter", "en" => "lyricist" },
    "rce" => { "de" => "Toningenieur", "en" => "recording engineer" },
    "rcd" => { "de" => "Tonmeister", "en" => "recordist" },
    "trc" => { "de" => "Transkribierer", "en" => "transcriber" },
    "anm" => { "de" => "Trickfilmzeichner", "en" => "animator" },
    "trl" => { "de" => "Übersetzer", "en" => "translator", "german_shortcut" => "Übers." },
    "orm" => { "de" => "Veranstalter", "en" => "organizer" },
    "aut" => { "de" => "Verfasser", "en" => "author" },
    "win" => { "de" => "Verfasser einer Einleitung", "en" => "writer of introduction" },
    "aft" => { "de" => "Verfasser eines Nachworts", "en" => "author of afterword, colophon etc." },
    "wpr" => { "de" => "Verfasser eines Vorworts", "en" => "writer of preface" },
    "wst" => { "de" => "Verfasser von ergänzendem Text", "en" => "writer of supplementary textual content" },
    "wal" => { "de" => "Verfasser von zusätzlichen Lyrics", "en" => "writer of added lyrics" },
    "wat" => { "de" => "Verfasser von Zusatztexten", "en" => "writer of added text" },
    "sll" => { "de" => "Verkäufer", "en" => "seller" },
    "dto" => { "de" => "Widmender", "en" => "dedicator" },
    "dte" => { "de" => "Widmungsempfänger", "en" => "dedicatee" },
    "ptf" => { "de" => "Zivilkläger", "en" => "plaintiff" },
    "com" => { "de" => "Zusammenstellender", "en" => "compiler" }
  }

  def self.to_german_shortcut(relationship_designator)
    MAPPING[relationship_designator].try do |_mapping|
      _mapping["german_shortcut"] || _mapping["de"]
    end
  end
end
