require_relative "../record"

Metacrunch::UBPB::Record::BEZIEHUNGSCODES = {
  rcp: "Adressat",
  dgs: "Akademischer Betreuer",
  dfd: "Angeklagter/Beklagter",
  ann: "Annotierende Person",
  arc: "Architekt",
  arr: "Arrangeur",
  std: "Art Director",
  prf: "Ausführender",
  csl: "Berater",
  ape: "Berufungsbeklagter/Revisionsbeklagter",
  apl: "Berufungskläger/Revisionskläger",
  ins: "Beschriftende Person",
  scl: "Bildhauer",
  vdg: "Bildregisseur",
  brl: "Brailleschriftpräger",
  bnd: "Buchbinder",
  bkd: "Buchgestalter",
  sgd: "Bühnenregisseur",
  chr: "Choreograph",
  edm: "Cutter",
  dsr: "Designer",
  cnd: "Dirigent",
  pan: "Diskussionsteilnehmer",
  aus: "Drehbuchautor",
  prt: "Drucker",
  plt: "Druckformhersteller",
  prm: "Druckgrafiker",
  own: "(Gegenwärtiger) Eigentümer",
  inv: "Erfinder",
  nrt: "Erzähler",
  tlp: "Fernsehproduzent",
  tld: "Fernsehregisseur",
  fmk: "Filmemacher",
  fmp: "Filmproduzent",
  fmd: "Filmregisseur",
  fds: "Filmvertrieb",
  cas: "Formgießer",
  pht: "Fotograf",
  fmo: "Früherer Eigentümer",
  hst: "Gastgeber",
  hnr: "Gefeierter",
  crt: "Gerichtsstenograf",
  stl: "Geschichtenerzähler",
  egr: "Graveur",
  isb: "Herausgebendes Organ",
  edt: "Herausgeber",
  rpc: "Hörfunkproduzent",
  rdd: "Hörfunkregisseur",
  ill: "Illustrator",
  itr: "Instrumentalmusiker",
  ivr: "Interviewer",
  ive: "Interviewter",
  ctg: "Kartograf",
  wac: "Kommentarverfasser",
  cmm: "Kommentator",
  cmp: "Komponist",
  cst: "Kostümbildner",
  cur: "Kurator",
  art: "Künstler",
  abr: "Kürzender",
  lsa: "Landschaftsarchitekt",
  srv: "Landvermesser",
  tch: "Lehrer",
  dpt: "Leihgeber",
  lbt: "Librettist",
  clt: "Lichtdrucker",
  ltg: "Lithograph",
  med: "Medium",
  ctb: "Mitwirkender",
  mod: "Moderator",
  msd: "Musikalischer Leiter",
  osp: "On-Screen-Präsentator",
  pre: "Präsentator",
  pra: "Praeses",
  pro: "Produzent",
  prg: "Programmierer",
  mtk: "Protokollant",
  ppt: "Puppenspieler",
  etr: "Radierer",
  spk: "Redner",
  drt: "Regisseur",
  cor: "Registrar",
  rsp: "Respondent",
  rsr: "Restaurator",
  jud: "Richter",
  sng: "Sänger",
  col: "Sammler",
  brd: "Sender",
  act: "Schauspieler",
  spn: "Sponsor",
  dnr: "Stifter",
  vac: "Synchronsprecher",
  prs: "Szenenbildner",
  dnc: "Tänzer",
  drm: "Technischer Zeichner",
  lyr: "Textdichter",
  rce: "Toningenieur",
  rcd: "Tonmeister",
  trc: "Transkribierer",
  anm: "Trickfilmzeichner",
  trl: "Übersetzer",
  orm: "Veranstalter",
  aut: "Verfasser",
  win: "Verfasser einer Einleitung",
  aft: "Verfasser eines Nachworts",
  wpr: "Verfasser eines Vorworts",
  wst: "Verfasser von ergänzendem Text",
  wal: "Verfasser von zusätzlichen Lyrics",
  wat: "Verfasser von Zusatztexten",
  sll: "Verkäufer",
  dto: "Widmender",
  dte: "Widmungsempfänger",
  ptf: "Zivilkläger",
  com: "Zusammenstellender"
}
